site_name: Alsfs documentation
pages:
    - Home: index.md
    - Demos: demos.md
    - Install: install.md
    - Alsfs Chrome Extension: alsfschromeextension.md
    - Alsfssrv: alsfssrv.md
    - Alsfs: alsfs.md
    - Fs-uae: fs-uae.md
theme: readthedocs
